#!/bin/sh
#
# Init oled module
#

DAEMON="Oled Module"


start() {

        probe_oled=$(i2cdetect -y -r 0|grep 3c)

        if [[ "$probe_oled" != "" ]]
        then
                printf 'Initialize %s...\n' "$DAEMON"

                # OLED init
                ssd1306_bin -I 128x64

                # clear whole screen
                ssd1306_bin -c

                # normal orientation display
                ssd1306_bin -r 0

                # turn on display
                ssd1306_bin -d 1

                # write string
                ssd1306_bin -l "Hi T113-s3"
        else
                printf '%s not found!\n' "$DAEMON"
        fi
}

stop() {
	printf 'Stopping %s...\n' "$DAEMON"
        # clear whole screen
        ssd1306_bin -c
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
